CREATE TABLE [EXTRACT_MDATA].[ExtractWatermarkLog_scd2]
(
	[EXTRACTNAME] [nvarchar](200) NOT NULL,
	[MODIFIEDDATETIME] [datetime2](7) NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO