CREATE VIEW [e4i].[Reconcile_SF_SourceToTargetHistory_V]
AS SELECT [LatestBatchDateTime]
      ,[SourceObject]
      ,[SourceObjectRowCount]
      ,[SourceQueryRowCount]
      ,[TargetCsvFileName]
      ,[RowsCopiedToCsvFile]
      ,[StgTableName]
      ,[StgTableRowCount]
      ,[StgTableToCsvFileRowDiff]
      ,[EdlMdataTableName]
      ,[EdlMdataTableRowCount]
      ,[EdlTableToSourceObjectRowDiff]
  FROM [e4i].[Reconcile_SF_SourceToTargetHistory];
GO
