CREATE PROC [EXTRACT_MDATA].[USP_EDL_D365_PRICING_PRICE_MATCH_D365] AS

BEGIN
SELECT
    PROFILELINE.MET_ITEMNUMBER AS ITEM_ID
    ,CASE WHEN PROFILELINE.MET_ATTACHMENTTYPEIDNAME= 'I - Item' THEN 'I'
          WHEN PROFILELINE.MET_ATTACHMENTTYPEIDNAME='S - Subrange' THEN 'S' ELSE ' ' END AS FAMILY_ID
    ,CUST.CUSTOPERGROUPID AS GROUP_CODE
    ,FORMAT(PROFILELINE.MET_VALIDFROM,'dd/MM/yyyy') AS START_DATE
    ,CASE WHEN PROFILELINE.MET_VALIDTO is NULL THEN ' ' ELSE FORMAT(PROFILELINE.MET_VALIDTO,'dd/MM/yyyy') END AS END_DATE
    ,FORMAT(PROFILELINE.MET_SRPPRICE,'0.00') AS AMOUNT
FROM [EDL_MDATA].[MET_PRICINGPROFILELINE] PROFILELINE
    LEFT OUTER JOIN EDL_MDATA.MET_PRICINGPROFILE PROFILE ON PROFILELINE.MET_PRICINGPROFILEID=PROFILE.MET_PRICINGPROFILEID
    LEFT OUTER JOIN EDL_D365.METCUSTTABLE CUST ON PROFILE.MET_ACCOUNTNUMBER=CUST.ACCOUNTNUM
        WHERE PROFILELINE.met_attachmenttypeidname IN ('I - Item','S - Subrange') 
              AND PROFILE.met_profiletypeidname IN ('Exception (Best of from nominated list of profiles)','Worst of (from nominated list of profiles)')
              AND PROFILE.IS_CURRENT_FLAG=1 
              AND PROFILE.IS_DELETE_FLAG=0 
              AND PROFILELINE.IS_CURRENT_FLAG=1 
              AND PROFILELINE.IS_DELETE_FLAG=0
           
END