CREATE PROC [EXTRACT_MDATA].[USP_EDL_D365_VENDOR_DynOutVM] @FullLoad [bit],@Batch_Run_Datetime [DATETIME2],@FileGenerationGroup [varchar](10) AS

-- set the precision of @batch_run_datetime (No longer needed as this is specified in [usp_call_Extract_SP]
-- DECLARE @batch_run_datetime_input as nvarchar(100) = FORMAT(@batch_run_datetime, 'yyyy-MM-dd HH:mm:ss.fff')

BEGIN

	SELECT
	[VENDORACCOUNTNUMBER],
	[ASSIGNEDSITE] ,
	[ASSIGNEDWH],
	[VENDORORGANIZATIONNAME],
	ACTION_CODE AS [FLAG],
	[DEFAULTPROCUMENTWAREHOUSEID],
	[PLANNERCODE],
	[VENDORBUSINESSADDRESSSTREET],
	[VENDORBUSINESSADDRESSCITY],
	[VENDORBUSINESSADDRESSSTATEID],
	[VENDORBUSINESSADDRESSZIPCODE],
	[VENDORBUSINESSADDRESSCOUNTRYREGIONID] ,
	[VENDORDELIVERYADDRESSSTREET],
	[VENDORDELIVERYADDRESSCITY] ,
	[VENDORDELIVERYADDRESSSTATEID],
	[VENDORDELIVERYADDRESSZIPCODE],
	[VENDORDELIVERYADDRESSCOUNTRYREGIONID],
	[VENDOROTHERADDRESSSTREET],
	[VENDOROTHERADDRESSCITY],
	[VENDOROTHERADDRESSSTATEID],
	[VENDOROTHERADDRESSZIPCODE],
	[VENDOROTHERADDRESSCOUNTRYREGIONID],
	[VENDORPRIMARYCONTACTPERSONID],
	[VENDORPRIMARYPHONENUMBER],
	[VENDORPRIMARYFAXNUMBER],
	[PRIMARYCONTACTPERSONID],
	[CONTACTPERSONNAME],
	[CONTACTPERSONADDRESSSTREET],
	[CONTACTPERSONADDRESSCITY],
	[CONTACTPERSONADDRESSSTATEID],
	[CONTACTPERSONADDRESSZIPCODE],
	[CONTACTPERSONADDRESSCOUNTRYREGIONID],
	[CONTACTPERSONPHONENUMBER]
	FROM [EXTRACT_MDATA].[EDL_D365_VENDOR_DynOutVM]
    WHERE Batch_Run_Datetime > @Batch_Run_Datetime
		AND FileGenerationGroup = @FileGenerationGroup
		AND IS_CURRENT_FLAG = 1
END
