CREATE PROC [EXTRACT_MDATA].[USP_EDL_D365_GET_STATE_NAME] @STATE_ID [VARCHAR](1) AS 

BEGIN

SELECT  CASE
        WHEN @STATE_ID='1' THEN 'NSW'
        WHEN @STATE_ID='2' THEN 'VIC'
        WHEN @STATE_ID='3' THEN 'QLD'
        WHEN @STATE_ID='4' THEN 'WA_'
        WHEN @STATE_ID='5' THEN 'SA_'
        WHEN @STATE_ID='6' THEN 'NT_'
        WHEN @STATE_ID='7' THEN 'TAS'
        WHEN @STATE_ID='8' THEN 'ACT'
        WHEN @STATE_ID='9' THEN 'NZ_' 
        ELSE NULL END AS STATE

END



