CREATE PROC [EXTRACT_MDATA].[USP_EDL_D365_DYN_REX_194] @STATE_CODE [VARCHAR] AS
BEGIN 

WITH DIST AS(

  SELECT DISTINCT ITEM_ID FROM [EXTRACT].[V_EDL_D365_REX_194]

)

  
SELECT T1.itemid
    , @state_code AS STATE_CODE
    , CASE WHEN T2.RATE IS NULL THEN 0 
    ELSE T2.RATE END AS RATE
FROM DIST AS T1
LEFT JOIN [EXTRACT].[V_EDL_D365_REX_194] AS T2
ON T1.itemid = T2.itemid
WHERE T2.STATE_CODE = @STATE_CODE

END



