CREATE PROC [EXTRACT_MDATA].[USP_EDL_D365_ITEM_COST_UPDATES] @WATERMARKLOG_DT [DATETIME] AS
BEGIN
	SET @WATERMARKLOG_DT = ISNULL(
		@WATERMARKLOG_DT, (
			SELECT MODIFIEDDATETIME 
			FROM [EXTRACT_MDATA].[EXTRACTWATERMARKLOG] 
			WHERE EXTRACTNAME = 'EDL_D365_ITEM_COST_UPDATES'
			)
		)
SELECT ItemNumber,
    WarehouseId,
    ProformaCost,
  	ActualCost,
    POListForPIM,
	ActMktSpreadCalcCode,
    ActMktSpreadCalcRate
FROM [EXTRACT_MDATA].[EDL_D365_ITEM_COST_UPDATES]
--WHERE UPDATED_DT > @WATERMARKLOG_DT 
--AND LEGALENTITY = @FILEGENERATIONGROUP
END