CREATE PROC [EXTRACT_MDATA].[usp_EDL_D365_ExciseDeviation_DSCILQSC] @FullLoad [bit],@Batch_Run_Datetime [DATETIME2],@FileGenerationGroup [varchar](10) AS

BEGIN

  SElECT
   'LQSTC' AS RECORD_ID,
    [ACTION_CODE] AS ACTIONCODE,
    LEFT(ISNULL(TARIFFITEM,' ')+REPLICATE(' ',13),13) AS [TARIFFITEM],
    LEFT(ISNULL(STATCODE,' ')+REPLICATE(' ',4),4) AS [STATCODE],
    LEFT(ISNULL(DESCRIPTION,' ')+REPLICATE(' ',30),30) AS [DESCRIPTION], 
	FORMAT([STRENGTHLESSOREQUAL] * 10,'000') AS [STRENGTHLESSOREQUAL], 
    FORMAT([STRENGTHGREATERTHAN] * 10,'000') AS [STRENGTHGREATERTHAN],
    FORMAT([ADVALOREMORBEERSUBSIDYRATE] * 100,'00000') AS [ADVALOREMORBEERSUBSIDYRATE],
    FORMAT([DUTYLAL] * 100,'00000') AS [DUTYLAL],
	'|' AS EndPipe
    FROM [EXTRACT_MDATA].[EDL_D365_ExciseDeviation_DSCILQSC]
    WHERE Batch_Run_Datetime >= @Batch_Run_Datetime
		AND FileGenerationGroup = @FileGenerationGroup
		AND IS_CURRENT_FLAG = 1

END