CREATE PROC [EXTRACT_MDATA].[USP_EDL_D365_INVENTORY_ASTK]  @FullLoad [bit],@Batch_Run_Datetime [DATETIME2],@FileGenerationGroup [varchar](10) AS
BEGIN
WITH HEADER_RECORD AS(
    select
    '00'														AS RECTYPE
    ,'01'														AS DATATYPE
    ,'R'														AS LOADTYPE
    ,'B'														AS LOADSCOPE
    ,Left(concat('00',@FileGenerationGroup)+REPLICATE(' ',6),6) AS SCOPEKEY
    ,CONCAT('PR01A2',' ',format(@Batch_Run_Datetime,'dd/MM/yyyy HH:MM'))	AS RUNTIME 
)
,DETAIL_RECORD AS (
	SELECT 
		17																AS RECTYPE
		, T3.DIVISION													AS PILLAR
		, T3.WAREHOUSE_STATE_CODE										AS STATE
		, RIGHT(rtrim('000000' + T1.ITEMID), 6)							AS ITEMNO 
		, T2.INVENTLOCATIONID											AS BRANCH
		, ' '															AS ACTION
		, CASE WHEN SUM(T1.AVAILPHYSICAL) + SUM(T1.ORDERED) + SUM(T1.ARRIVED) - SUM(T1.RESERVORDERED) - SUM(T1.ONORDER) < 0 
			THEN  '00000' 
			ELSE FORMAT(SUM(T1.AVAILPHYSICAL) + SUM(T1.ORDERED) + SUM(T1.ARRIVED) - SUM(T1.RESERVORDERED) - SUM(T1.ONORDER), '00000')
			END 														AS SOH
		, CASE WHEN T1.INVENTSTATUSID = 'Available' 
			then 'A' 
			else 'N' 
			end															AS STKFLG
	FROM EDL_D365.INVENTSUM T1 
	LEFT JOIN EDL_D365.INVENTDIM T2 
		ON  T1.INVENTDIMID = T2.INVENTDIMID AND
			T1.DATAAREAID = T2.DATAAREAID AND 
			T1.PARTITION = T2.PARTITION AND
			T2.IS_CURRENT_FLAG = 1 AND T2.IS_DELETE_FLAG = 0
	LEFT JOIN EDL_MDATA.XDOCK_Location T3
		ON T2.INVENTLOCATIONID  = T3.LOCATION_ID 
	WHERE T1.CLOSEDQTY = 0 
		AND T3.WAREHOUSE_STATE_CODE IS NOT NULL 
		AND T1.DATAAREAID = '2000' 
		AND T3.DIVISION IN ('ALM')
		AND T1.InventStatusId IS NOT NULL
		AND T1.IS_CURRENT_FLAG = 1 AND T1.IS_DELETE_FLAG = 0
		AND T3.WAREHOUSE_STATE_CODE = @FileGenerationGroup
	GROUP BY T3.DIVISION
	, T3.WAREHOUSE_STATE_CODE
	, T1.ITEMID
	, T2.INVENTLOCATIONID
	, CASE WHEN T1.INVENTSTATUSID = 'Available' 
			then 'A' 
			else 'N' 
			end
)
,TRAILER_RECORD AS(
    SELECT
        '99' AS RECTYPE
        ,COUNT(*) AS RECORD_COUNT
    FROM DETAIL_RECORD
)
,FINAL AS
(
    SELECT
    CONCAT(RECTYPE,'|',DATATYPE,'|',LOADTYPE,'|',LOADSCOPE,'|',SCOPEKEY,'|',RUNTIME,'|') AS DATA
    FROM HEADER_RECORD
    UNION ALL
    SELECT
    CONCAT(RECTYPE,'|',PILLAR,'|',STATE,'|',ITEMNO,'|',BRANCH,'|',ACTION,'|',SOH,'|',STKFLG,'|') AS DATA
    FROM DETAIL_RECORD   
    UNION ALL
    SELECT
    CONCAT(RECTYPE,'|',RECORD_COUNT,'|') AS DATA
    FROM TRAILER_RECORD
)
  select * FROM FINAL order by 1 ASC;
END	

GO